<?php

namespace ContainerLxABjxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6HacvtYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6HacvtY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6HacvtY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipeRepository' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
        ], [
            'equipeRepository' => 'App\\Repository\\EquipeRepository',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
        ]);
    }
}
