<?php

namespace ContainerLxABjxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YYPgznkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yYPgznk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yYPgznk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'equipeRepo' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
        ], [
            'em' => '?',
            'equipeRepo' => 'App\\Repository\\EquipeRepository',
        ]);
    }
}
