<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxABjxb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxABjxb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxABjxb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxABjxb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLxABjxb\App_KernelDevDebugContainer([
    'container.build_hash' => 'LxABjxb',
    'container.build_id' => '68a494d3',
    'container.build_time' => 1630510652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxABjxb');
